//
//  CurrentParl.swift
//  polCal-v2
//
//  Created by Lukas on 24/10/2024.
//

import Foundation
import SwiftData

let legpartySLOVENSKO = legParty(id: 4, name: "OĽaNO")
let legpartySMERSD = legParty(id: 1, name: "SMER–SD")
let legpartySNS = legParty(id: 7,name: "SNS")
let legpartySAS = legParty(id: 5,name: "SAS")
let legpartyKDH = legParty(id: 6,name: "KDH")
let legpartyPS = legParty(id: 2, name: "PS")
let legpartyHLASSD = legParty(id: 3,name: "HLAS–SD")



let mp1 = MP(name: "Vladimír Baláž", legParty: legpartySMERSD)
let mp2 = MP(name: "Jaroslav Baška", legParty: legpartySMERSD)
let mp3 = MP(name: "Marcela Čavojová", legParty: legpartySMERSD)
let mp4 = MP(name: "Vladimír Faič", legParty: legpartySMERSD)
let mp5 = MP(name: "Dušan Galis", legParty: legpartySMERSD)
let mp6 = MP(name: "Tibor Gašpar", legParty: legpartySMERSD)
let mp7 = MP(name: "Richard Glück", legParty: legpartySMERSD)
let mp8 = MP(name: "Pavol Goga", legParty: legpartySMERSD)
let mp9 = MP(name: "Jozef Habánik", legParty: legpartySMERSD)
let mp10 = MP(name: "Augustín Hambálek", legParty: legpartySMERSD)
let mp11 = MP(name: "Ivan Hazucha", legParty: legpartySMERSD)
let mp12 = MP(name: "Ján Horváth", legParty: legpartySMERSD)
let mp13 = MP(name: "Dušan Jarjabek", legParty: legpartySMERSD)
let mp14 = MP(name: "Jozef Ježík", legParty: legpartySMERSD)
let mp15 = MP(name: "Jozef Kačmár", legParty: legpartySMERSD)
let mp16 = MP(name: "Michal Kapuš", legParty: legpartySMERSD)
let mp17 = MP(name: "Daniel Karas", legParty: legpartySMERSD)
let mp18 = MP(name: "Marián Kéry", legParty: legpartySMERSD)
let mp19 = MP(name: "Stanislav Kubánek", legParty: legpartySMERSD)
let mp20 = MP(name: "Ján Kvorka", legParty: legpartySMERSD)
let mp21 = MP(name: "Boleslav Lešo", legParty: legpartySMERSD)
let mp22 = MP(name: "Michal Lukša", legParty: legpartySMERSD)
let mp23 = MP(name: "Zuzana Matejičková", legParty: legpartySMERSD)
let mp24 = MP(name: "Ján Mažgút", legParty: legpartySMERSD)
let mp25 = MP(name: "Jaroslav Mego", legParty: legpartySMERSD)
let mp26 = MP(name: "František Petro", legParty: legpartySMERSD)
let mp27 = MP(name: "Zuzana Plevíková", legParty: legpartySMERSD)
let mp28 = MP(name: "Ján Podmanický", legParty: legpartySMERSD)
let mp29 = MP(name: "Ján Richter", legParty: legpartySMERSD)
let mp30 = MP(name: "Marián Saloň", legParty: legpartySMERSD)
let mp31 = MP(name: "Justín Sedlák", legParty: legpartySMERSD)
let mp32 = MP(name: "Andrej Sitkár", legParty: legpartySMERSD)
let mp33 = MP(name: "Peter Sokol", legParty: legpartySMERSD)
let mp34 = MP(name: "Anton Stredák", legParty: legpartySMERSD)
let mp35 = MP(name: "Michal Stuška", legParty: legpartySMERSD)
let mp36 = MP(name: "Peter Šuca", legParty: legpartySMERSD)
let mp37 = MP(name: "Igor Válek", legParty: legpartySMERSD)
let mp38 = MP(name: "Jozef Valocký", legParty: legpartySMERSD)
let mp39 = MP(name: "Jana Vaľová", legParty: legpartySMERSD)
let mp40 = MP(name: "Ľubomír Vážny", legParty: legpartySMERSD)
let mp41 = MP(name: "Viliam Zahorčák", legParty: legpartySMERSD)

let mp42 = MP(name: "Jana Bittó Cigániková", legParty: legpartySAS)
let mp43 = MP(name: "Ondrej Dostál", legParty: legpartySAS)
let mp44 = MP(name: "Karol Galek", legParty: legpartySAS)
let mp45 = MP(name: "Branislav Gröhling", legParty: legpartySAS)
let mp46 = MP(name: "Alojz Hlina", legParty: legpartySAS)
let mp47 = MP(name: "Mária Kolíková", legParty: legpartySAS)
let mp48 = MP(name: "Juraj Krúpa", legParty: legpartySAS)
let mp49 = MP(name: "Vladimír Ledecký", legParty: legpartySAS)
let mp50 = MP(name: "Vladimíra Marcinková", legParty: legpartySAS)
let mp51 = MP(name: "Tomáš Szalay", legParty: legpartySAS)
let mp52 = MP(name: "Marián Viskupič", legParty: legpartySAS)

let mp53 = MP(name: "Andrej Danko", legParty: legpartySNS)
let mp54 = MP(name: "Karol Farkašovský", legParty: legpartySNS)
let mp55 = MP(name: "Milan Garaj", legParty: legpartySNS)
let mp56 = MP(name: "Peter Kotlár", legParty: legpartySNS)
let mp57 = MP(name: "Dagmar Kramplová", legParty: legpartySNS)
let mp58 = MP(name: "Adam Lučanský", legParty: legpartySNS)
let mp59 = MP(name: "Roman Michelko", legParty: legpartySNS)
let mp60 = MP(name: "Dušan Muňko", legParty: legpartySNS)

let mp61 = MP(name: "Marián Čaučík", legParty: legpartyKDH)
let mp62 = MP(name: "Jozef Hajko", legParty: legpartyKDH)
let mp63 = MP(name: "Ján Horecký", legParty: legpartyKDH)
let mp64 = MP(name: "Igor Janckulík", legParty: legpartyKDH)
let mp65 = MP(name: "František Majerský", legParty: legpartyKDH)
let mp66 = MP(name: "Milan Majerský", legParty: legpartyKDH)
let mp67 = MP(name: "František Mikloško", legParty: legpartyKDH)
let mp68 = MP(name: "Peter Stachura", legParty: legpartyKDH)
let mp69 = MP(name: "Branislav Škripek", legParty: legpartyKDH)
let mp70 = MP(name: "Martin Šmilňák", legParty: legpartyKDH)
let mp71 = MP(name: "Andrea Turčanová", legParty: legpartyKDH)

let mp72 = MP(name: "Michal Bartek", legParty: legpartyHLASSD)
let mp73 = MP(name: "Branislav Becík", legParty: legpartyHLASSD)
let mp74 = MP(name: "Ján Blcháč", legParty: legpartyHLASSD)
let mp75 = MP(name: "Jozef Cech", legParty: legpartyHLASSD)
let mp76 = MP(name: "Miroslav Čellár", legParty: legpartyHLASSD)
let mp77 = MP(name: "Dávid Demečko", legParty: legpartyHLASSD)
let mp78 = MP(name: "Richard Eliáš", legParty: legpartyHLASSD)
let mp79 = MP(name: "Ján Ferenčák", legParty: legpartyHLASSD)
let mp80 = MP(name: "Štefan Gašparovič", legParty: legpartyHLASSD)
let mp81 = MP(name: "Karol Janas", legParty: legpartyHLASSD)
let mp82 = MP(name: "Peter Kalivoda", legParty: legpartyHLASSD)
let mp83 = MP(name: "Ľubica Laššáková", legParty: legpartyHLASSD)
let mp84 = MP(name: "Zdenka Mačicová", legParty: legpartyHLASSD)
let mp85 = MP(name: "Roman Malatinec", legParty: legpartyHLASSD)
let mp86 = MP(name: "Samuel Migaľ", legParty: legpartyHLASSD)
let mp87 = MP(name: "Peter Náhlik", legParty: legpartyHLASSD)
let mp88 = MP(name: "Alena Nováková", legParty: legpartyHLASSD)
let mp89 = MP(name: "Róbert Puci", legParty: legpartyHLASSD)
let mp90 = MP(name: "Paula Puškárová", legParty: legpartyHLASSD)
let mp91 = MP(name: "Peter Slyško", legParty: legpartyHLASSD)
let mp92 = MP(name: "Zdenko Svoboda", legParty: legpartyHLASSD)
let mp93 = MP(name: "Andrea Szabóová", legParty: legpartyHLASSD)
let mp94 = MP(name: "Radomír Šalitroš", legParty: legpartyHLASSD)
let mp95 = MP(name: "Igor Šimko", legParty: legpartyHLASSD)
let mp96 = MP(name: "Dušan Tittel", legParty: legpartyHLASSD)
let mp97 = MP(name: "Erik Vlček", legParty: legpartyHLASSD)
let mp98 = MP(name: "Peter Žiga", legParty: legpartyHLASSD)

let mp99 = MP(name: "Irena Bihariová", legParty: legpartyPS)
let mp100 = MP(name: "Dávid Dej", legParty: legpartyPS)
let mp101 = MP(name: "Martin Dubéci", legParty: legpartyPS)
let mp102 = MP(name: "Richard Dubovický", legParty: legpartyPS)
let mp103 = MP(name: "Oskar Dvořák", legParty: legpartyPS)
let mp104 = MP(name: "Tina Gažovičová", legParty: legpartyPS)
let mp105 = MP(name: "Jana Hanuliaková", legParty: legpartyPS)
let mp106 = MP(name: "Ján Hargaš", legParty: legpartyPS)
let mp107 = MP(name: "Zora Jaurová", legParty: legpartyPS)
let mp108 = MP(name: "Beáta Jurík", legParty: legpartyPS)
let mp109 = MP(name: "Viera Kalmárová", legParty: legpartyPS)
let mp110 = MP(name: "Štefan Kišš", legParty: legpartyPS)
let mp111 = MP(name: "Dana Kleinert", legParty: legpartyPS)
let mp112 = MP(name: "Ingrid Kosová", legParty: legpartyPS)
let mp113 = MP(name: "Marek Lackovič", legParty: legpartyPS)
let mp114 = MP(name: "Darina Luščíková", legParty: legpartyPS)
let mp115 = MP(name: "Zuzana Mesterová", legParty: legpartyPS)
let mp116 = MP(name: "Natália Nash", legParty: legpartyPS)
let mp117 = MP(name: "Simona Petrík", legParty: legpartyPS)
let mp118 = MP(name: "Lucia Plaváková", legParty: legpartyPS)
let mp119 = MP(name: "Ondrej Prostredník", legParty: legpartyPS)
let mp120 = MP(name: "Michal Sabo", legParty: legpartyPS)
let mp121 = MP(name: "Jaroslav Spišiak", legParty: legpartyPS)
let mp122 = MP(name: "Tamara Stohlová", legParty: legpartyPS)
let mp123 = MP(name: "Michal Šimečka", legParty: legpartyPS)
let mp124 = MP(name: "Veronika Šrobová", legParty: legpartyPS)
let mp125 = MP(name: "Ivan Štefunko", legParty: legpartyPS)
let mp126 = MP(name: "Zuzana Števulová", legParty: legpartyPS)
let mp127 = MP(name: "Viliam Tankó", legParty: legpartyPS)
let mp128 = MP(name: "Michal Truban", legParty: legpartyPS)
let mp129 = MP(name: "Tomáš Valášek", legParty: legpartyPS)
let mp130 = MP(name: "Branislav Vančo", legParty: legpartyPS)
let mp131 = MP(name: "Veronika Veslárová", legParty: legpartyPS)

let mp132 = MP(name: "Lukáš Bužo", legParty: legpartySLOVENSKO)
let mp133 = MP(name: "Gábor Grendel", legParty: legpartySLOVENSKO)
let mp134 = MP(name: "Július Jakab", legParty: legpartySLOVENSKO)
let mp135 = MP(name: "Marek Krajčí", legParty: legpartySLOVENSKO)
let mp136 = MP(name: "Rastislav Krátky", legParty: legpartySLOVENSKO)
let mp137 = MP(name: "Igor Matovič", legParty: legpartySLOVENSKO)
let mp138 = MP(name: "Roman Mikulec", legParty: legpartySLOVENSKO)
let mp139 = MP(name: "Peter Pollák", legParty: legpartySLOVENSKO)
let mp140 = MP(name: "Jozef Pročko", legParty: legpartySLOVENSKO)
let mp141 = MP(name: "Veronika Remišová", legParty: legpartySLOVENSKO)
let mp142 = MP(name: "Michal Šipoš", legParty: legpartySLOVENSKO)
let mp143 = MP(name: "Anežka Škopová", legParty: legpartySLOVENSKO)
let mp144 = MP(name: "Richard Vašečka", legParty: legpartySLOVENSKO)
let mp145 = MP(name: "Anna Záborská", legParty: legpartySLOVENSKO)

let mp146 = MP(name: "Martina Holečková")
let mp147 = MP(name: "Rudolf Huliak")
let mp148 = MP(name: "Pavel Ľupták")
let mp149 = MP(name: "Ivan Ševčík")
let mp150 = MP(name: "Ľubomír Galko")

let currentMPs: [MP] = [
    mp1, mp2, mp3, mp4, mp5, mp6, mp7, mp8, mp9, mp10,
    mp11, mp12, mp13, mp14, mp15, mp16, mp17, mp18, mp19, mp20,
    mp21, mp22, mp23, mp24, mp25, mp26, mp27, mp28, mp29, mp30,
    mp31, mp32, mp33, mp34, mp35, mp36, mp37, mp38, mp39, mp40,
    mp41, mp42, mp43, mp44, mp45, mp46, mp47, mp48, mp49, mp50,
    mp51, mp52, mp53, mp54, mp55, mp56, mp57, mp58, mp59, mp60,
    mp61, mp62, mp63, mp64, mp65, mp66, mp67, mp68, mp69, mp70,
    mp71, mp72, mp73, mp74, mp75, mp76, mp77, mp78, mp79, mp80,
    mp81, mp82, mp83, mp84, mp85, mp86, mp87, mp88, mp89, mp90,
    mp91, mp92, mp93, mp94, mp95, mp96, mp97, mp98, mp99, mp100,
    mp101, mp102, mp103, mp104, mp105, mp106, mp107, mp108, mp109, mp110,
    mp111, mp112, mp113, mp114, mp115, mp116, mp117, mp118, mp119, mp120,
    mp121, mp122, mp123, mp124, mp125, mp126, mp127, mp128, mp129, mp130,
    mp131, mp132, mp133, mp134, mp135, mp136, mp137, mp138, mp139, mp140,
    mp141, mp142, mp143, mp144, mp145, mp146, mp147, mp148, mp149, mp150
]
