//
//  CurrentParl.swift
//  polCal-v2
//
//  Created by Lukas on 24/10/2024.
//

import Foundation
import SwiftData

let legpartySLOVENSKO = legParty(name: "OĽaNO")
let legpartySMERSD = legParty(name: "SMER–SD")
let legpartySNS = legParty(name: "SNS")
let legpartySAS = legParty(name: "SAS")
let legpartyKDH = legParty(name: "KDH")
let legpartyPS = legParty(name: "PS")
let legpartyHLASSD = legParty(name: "HLAS-SD")


let mp1 = MP(name: "Vladimír Baláž")
let mp2 = MP(name: "Jaroslav Baška")
let mp3 = MP(name: "Marcela Čavojová")
let mp4 = MP(name: "Vladimír Faič")
let mp5 = MP(name: "Dušan Galis")
let mp6 = MP(name: "Tibor Gašpar")
let mp7 = MP(name: "Richard Glück")
let mp8 = MP(name: "Pavol Goga")
let mp9 = MP(name: "Jozef Habánik")
let mp10 = MP(name: "Augustín Hambálek")
let mp11 = MP(name: "Ivan Hazucha")
let mp12 = MP(name: "Ján Horváth")
let mp13 = MP(name: "Dušan Jarjabek")
let mp14 = MP(name: "Jozef Ježík")
let mp15 = MP(name: "Jozef Kačmár")
let mp16 = MP(name: "Michal Kapuš")
let mp17 = MP(name: "Daniel Karas")
let mp18 = MP(name: "Marián Kéry")
let mp19 = MP(name: "Stanislav Kubánek")
let mp20 = MP(name: "Ján Kvorka")
let mp21 = MP(name: "Boleslav Lešo")
let mp22 = MP(name: "Michal Lukša")
let mp23 = MP(name: "Zuzana Matejičková")
let mp24 = MP(name: "Ján Mažgút")
let mp25 = MP(name: "Jaroslav Mego")
let mp26 = MP(name: "František Petro")
let mp27 = MP(name: "Zuzana Plevíková")
let mp28 = MP(name: "Ján Podmanický")
let mp29 = MP(name: "Ján Richter")
let mp30 = MP(name: "Marián Saloň")
let mp31 = MP(name: "Justín Sedlák")
let mp32 = MP(name: "Andrej Sitkár")
let mp33 = MP(name: "Peter Sokol")
let mp34 = MP(name: "Anton Stredák")
let mp35 = MP(name: "Michal Stuška")
let mp36 = MP(name: "Peter Šuca")
let mp37 = MP(name: "Igor Válek")
let mp38 = MP(name: "Jozef Valocký")
let mp39 = MP(name: "Jana Vaľová")
let mp40 = MP(name: "Ľubomír Vážny")
let mp41 = MP(name: "Viliam Zahorčák")

let mp42 = MP(name: "Jana Bittó Cigániková")
let mp43 = MP(name: "Ondrej Dostál")
let mp44 = MP(name: "Karol Galek")
let mp45 = MP(name: "Branislav Gröhling")
let mp46 = MP(name: "Alojz Hlina")
let mp47 = MP(name: "Mária Kolíková")
let mp48 = MP(name: "Juraj Krúpa")
let mp49 = MP(name: "Vladimír Ledecký")
let mp50 = MP(name: "Vladimíra Marcinková")
let mp51 = MP(name: "Tomáš Szalay")
let mp52 = MP(name: "Marián Viskupič")

let mp53 = MP(name: "Andrej Danko")
let mp54 = MP(name: "Karol Farkašovský")
let mp55 = MP(name: "Milan Garaj")
let mp56 = MP(name: "Peter Kotlár")
let mp57 = MP(name: "Dagmar Kramplová")
let mp58 = MP(name: "Adam Lučanský")
let mp59 = MP(name: "Roman Michelko")
let mp60 = MP(name: "Dušan Muňko")

let mp61 = MP(name: "Marián Čaučík")
let mp62 = MP(name: "Jozef Hajko")
let mp63 = MP(name: "Ján Horecký")
let mp64 = MP(name: "Igor Janckulík")
let mp65 = MP(name: "František Majerský")
let mp66 = MP(name: "Milan Majerský")
let mp67 = MP(name: "František Mikloško")
let mp68 = MP(name: "Peter Stachura")
let mp69 = MP(name: "Branislav Škripek")
let mp70 = MP(name: "Martin Šmilňák")
let mp71 = MP(name: "Andrea Turčanová")

let mp72 = MP(name: "Michal Bartek")
let mp73 = MP(name: "Branislav Becík")
let mp74 = MP(name: "Ján Blcháč")
let mp75 = MP(name: "Jozef Cech")
let mp76 = MP(name: "Miroslav Čellár")
let mp77 = MP(name: "Dávid Demečko")
let mp78 = MP(name: "Richard Eliáš")
let mp79 = MP(name: "Ján Ferenčák")
let mp80 = MP(name: "Štefan Gašparovič")
let mp81 = MP(name: "Karol Janas")
let mp82 = MP(name: "Peter Kalivoda")
let mp83 = MP(name: "Ľubica Laššáková")
let mp84 = MP(name: "Zdenka Mačicová")
let mp85 = MP(name: "Roman Malatinec")
let mp86 = MP(name: "Samuel Migaľ")
let mp87 = MP(name: "Peter Náhlik")
let mp88 = MP(name: "Alena Nováková")
let mp89 = MP(name: "Róbert Puci")
let mp90 = MP(name: "Paula Puškárová")
let mp91 = MP(name: "Peter Slyško")
let mp92 = MP(name: "Zdenko Svoboda")
let mp93 = MP(name: "Andrea Szabóová")
let mp94 = MP(name: "Radomír Šalitroš")
let mp95 = MP(name: "Igor Šimko")
let mp96 = MP(name: "Dušan Tittel")
let mp97 = MP(name: "Erik Vlček")
let mp98 = MP(name: "Peter Žiga")

let mp99 = MP(name: "Irena Bihariová")
let mp100 = MP(name: "Dávid Dej")
let mp101 = MP(name: "Martin Dubéci")
let mp102 = MP(name: "Richard Dubovický")
let mp103 = MP(name: "Oskar Dvořák")
let mp104 = MP(name: "Tina Gažovičová")
let mp105 = MP(name: "Jana Hanuliaková")
let mp106 = MP(name: "Ján Hargaš")
let mp107 = MP(name: "Zora Jaurová")
let mp108 = MP(name: "Beáta Jurík")
let mp109 = MP(name: "Viera Kalmárová")
let mp110 = MP(name: "Štefan Kišš")
let mp111 = MP(name: "Dana Kleinert")
let mp112 = MP(name: "Ingrid Kosová")
let mp113 = MP(name: "Marek Lackovič")
let mp114 = MP(name: "Darina Luščíková")
let mp115 = MP(name: "Zuzana Mesterová")
let mp116 = MP(name: "Natália Nash")
let mp117 = MP(name: "Simona Petrík")
let mp118 = MP(name: "Lucia Plaváková")
let mp119 = MP(name: "Ondrej Prostredník")
let mp120 = MP(name: "Michal Sabo")
let mp121 = MP(name: "Jaroslav Spišiak")
let mp122 = MP(name: "Tamara Stohlová")
let mp123 = MP(name: "Michal Šimečka")
let mp124 = MP(name: "Veronika Šrobová")
let mp125 = MP(name: "Ivan Štefunko")
let mp126 = MP(name: "Zuzana Števulová")
let mp127 = MP(name: "Viliam Tankó")
let mp128 = MP(name: "Michal Truban")
let mp129 = MP(name: "Tomáš Valášek")
let mp130 = MP(name: "Branislav Vančo")
let mp131 = MP(name: "Veronika Veslárová")

let mp132 = MP(name: "Lukáš Bužo")
let mp133 = MP(name: "Gábor Grendel")
let mp134 = MP(name: "Július Jakab")
let mp135 = MP(name: "Marek Krajčí")
let mp136 = MP(name: "Rastislav Krátky")
let mp137 = MP(name: "Igor Matovič")
let mp138 = MP(name: "Roman Mikulec")
let mp139 = MP(name: "Peter Pollák")
let mp140 = MP(name: "Jozef Pročko")
let mp141 = MP(name: "Veronika Remišová")
let mp142 = MP(name: "Michal Šipoš")
let mp143 = MP(name: "Anežka Škopová")
let mp144 = MP(name: "Richard Vašečka")
let mp145 = MP(name: "Anna Záborská")
