//
//  CurrentParl.swift
//  polCal-v2
//
//  Created by Lukas on 24/10/2024.
//

import Foundation
import SwiftData

let legpartySLOVENSKO = legPartyModel(id: 4, name: "OĽaNO")
let legpartySMERSD = legPartyModel(id: 1, name: "SMER–SD")
let legpartySNS = legPartyModel(id: 7,name: "SNS")
let legpartySAS = legPartyModel(id: 5,name: "SAS")
let legpartyKDH = legPartyModel(id: 6,name: "KDH")
let legpartyPS = legPartyModel(id: 2, name: "PS")
let legpartyHLASSD = legPartyModel(id: 3,name: "HLAS–SD")



let mp1 = MPModel(name: "Vladimír Baláž", legParty: legpartySMERSD)
let mp2 = MPModel(name: "Jaroslav Baška", legParty: legpartySMERSD)
let mp3 = MPModel(name: "Marcela Čavojová", legParty: legpartySMERSD)
let mp4 = MPModel(name: "Vladimír Faič", legParty: legpartySMERSD)
let mp5 = MPModel(name: "Dušan Galis", legParty: legpartySMERSD)
let mp6 = MPModel(name: "Tibor Gašpar", legParty: legpartySMERSD)
let mp7 = MPModel(name: "Richard Glück", legParty: legpartySMERSD)
let mp8 = MPModel(name: "Pavol Goga", legParty: legpartySMERSD)
let mp9 = MPModel(name: "Jozef Habánik", legParty: legpartySMERSD)
let mp10 = MPModel(name: "Augustín Hambálek", legParty: legpartySMERSD)
let mp11 = MPModel(name: "Ivan Hazucha", legParty: legpartySMERSD)
let mp12 = MPModel(name: "Ján Horváth", legParty: legpartySMERSD)
let mp13 = MPModel(name: "Dušan Jarjabek", legParty: legpartySMERSD)
let mp14 = MPModel(name: "Jozef Ježík", legParty: legpartySMERSD)
let mp15 = MPModel(name: "Jozef Kačmár", legParty: legpartySMERSD)
let mp16 = MPModel(name: "Michal Kapuš", legParty: legpartySMERSD)
let mp17 = MPModel(name: "Daniel Karas", legParty: legpartySMERSD)
let mp18 = MPModel(name: "Marián Kéry", legParty: legpartySMERSD)
let mp19 = MPModel(name: "Stanislav Kubánek", legParty: legpartySMERSD)
let mp20 = MPModel(name: "Ján Kvorka", legParty: legpartySMERSD)
let mp21 = MPModel(name: "Boleslav Lešo", legParty: legpartySMERSD)
let mp22 = MPModel(name: "Michal Lukša", legParty: legpartySMERSD)
let mp23 = MPModel(name: "Zuzana Matejičková", legParty: legpartySMERSD)
let mp24 = MPModel(name: "Ján Mažgút", legParty: legpartySMERSD)
let mp25 = MPModel(name: "Jaroslav Mego", legParty: legpartySMERSD)
let mp26 = MPModel(name: "František Petro", legParty: legpartySMERSD)
let mp27 = MPModel(name: "Zuzana Plevíková", legParty: legpartySMERSD)
let mp28 = MPModel(name: "Ján Podmanický", legParty: legpartySMERSD)
let mp29 = MPModel(name: "Ján Richter", legParty: legpartySMERSD)
let mp30 = MPModel(name: "Marián Saloň", legParty: legpartySMERSD)
let mp31 = MPModel(name: "Justín Sedlák", legParty: legpartySMERSD)
let mp32 = MPModel(name: "Andrej Sitkár", legParty: legpartySMERSD)
let mp33 = MPModel(name: "Peter Sokol", legParty: legpartySMERSD)
let mp34 = MPModel(name: "Anton Stredák", legParty: legpartySMERSD)
let mp35 = MPModel(name: "Michal Stuška", legParty: legpartySMERSD)
let mp36 = MPModel(name: "Peter Šuca", legParty: legpartySMERSD)
let mp37 = MPModel(name: "Igor Válek", legParty: legpartySMERSD)
let mp38 = MPModel(name: "Jozef Valocký", legParty: legpartySMERSD)
let mp39 = MPModel(name: "Jana Vaľová", legParty: legpartySMERSD)
let mp40 = MPModel(name: "Ľubomír Vážny", legParty: legpartySMERSD)
let mp41 = MPModel(name: "Viliam Zahorčák", legParty: legpartySMERSD)

let mp42 = MPModel(name: "Jana Bittó Cigániková", legParty: legpartySAS)
let mp43 = MPModel(name: "Ondrej Dostál", legParty: legpartySAS)
let mp44 = MPModel(name: "Karol Galek", legParty: legpartySAS)
let mp45 = MPModel(name: "Branislav Gröhling", legParty: legpartySAS)
let mp46 = MPModel(name: "Alojz Hlina", legParty: legpartySAS)
let mp47 = MPModel(name: "Mária Kolíková", legParty: legpartySAS)
let mp48 = MPModel(name: "Juraj Krúpa", legParty: legpartySAS)
let mp49 = MPModel(name: "Vladimír Ledecký", legParty: legpartySAS)
let mp50 = MPModel(name: "Vladimíra Marcinková", legParty: legpartySAS)
let mp51 = MPModel(name: "Tomáš Szalay", legParty: legpartySAS)
let mp52 = MPModel(name: "Marián Viskupič", legParty: legpartySAS)

let mp53 = MPModel(name: "Andrej Danko", legParty: legpartySNS)
let mp54 = MPModel(name: "Karol Farkašovský", legParty: legpartySNS)
let mp55 = MPModel(name: "Milan Garaj", legParty: legpartySNS)
let mp56 = MPModel(name: "Peter Kotlár", legParty: legpartySNS)
let mp57 = MPModel(name: "Dagmar Kramplová", legParty: legpartySNS)
let mp58 = MPModel(name: "Adam Lučanský", legParty: legpartySNS)
let mp59 = MPModel(name: "Roman Michelko", legParty: legpartySNS)
let mp60 = MPModel(name: "Dušan Muňko", legParty: legpartySNS)

let mp61 = MPModel(name: "Marián Čaučík", legParty: legpartyKDH)
let mp62 = MPModel(name: "Jozef Hajko", legParty: legpartyKDH)
let mp63 = MPModel(name: "Ján Horecký", legParty: legpartyKDH)
let mp64 = MPModel(name: "Igor Janckulík", legParty: legpartyKDH)
let mp65 = MPModel(name: "František Majerský", legParty: legpartyKDH)
let mp66 = MPModel(name: "Milan Majerský", legParty: legpartyKDH)
let mp67 = MPModel(name: "František Mikloško", legParty: legpartyKDH)
let mp68 = MPModel(name: "Peter Stachura", legParty: legpartyKDH)
let mp69 = MPModel(name: "Branislav Škripek", legParty: legpartyKDH)
let mp70 = MPModel(name: "Martin Šmilňák", legParty: legpartyKDH)
let mp71 = MPModel(name: "Andrea Turčanová", legParty: legpartyKDH)

let mp72 = MPModel(name: "Michal Bartek", legParty: legpartyHLASSD)
let mp73 = MPModel(name: "Branislav Becík", legParty: legpartyHLASSD)
let mp74 = MPModel(name: "Ján Blcháč", legParty: legpartyHLASSD)
let mp75 = MPModel(name: "Jozef Cech", legParty: legpartyHLASSD)
let mp76 = MPModel(name: "Miroslav Čellár", legParty: legpartyHLASSD)
let mp77 = MPModel(name: "Dávid Demečko", legParty: legpartyHLASSD)
let mp78 = MPModel(name: "Richard Eliáš", legParty: legpartyHLASSD)
let mp79 = MPModel(name: "Ján Ferenčák", legParty: legpartyHLASSD)
let mp80 = MPModel(name: "Štefan Gašparovič", legParty: legpartyHLASSD)
let mp81 = MPModel(name: "Karol Janas", legParty: legpartyHLASSD)
let mp82 = MPModel(name: "Peter Kalivoda", legParty: legpartyHLASSD)
let mp83 = MPModel(name: "Ľubica Laššáková", legParty: legpartyHLASSD)
let mp84 = MPModel(name: "Zdenka Mačicová", legParty: legpartyHLASSD)
let mp85 = MPModel(name: "Roman Malatinec", legParty: legpartyHLASSD)
let mp86 = MPModel(name: "Samuel Migaľ", legParty: legpartyHLASSD)
let mp87 = MPModel(name: "Peter Náhlik", legParty: legpartyHLASSD)
let mp88 = MPModel(name: "Alena Nováková", legParty: legpartyHLASSD)
let mp89 = MPModel(name: "Róbert Puci", legParty: legpartyHLASSD)
let mp90 = MPModel(name: "Paula Puškárová", legParty: legpartyHLASSD)
let mp91 = MPModel(name: "Peter Slyško", legParty: legpartyHLASSD)
let mp92 = MPModel(name: "Zdenko Svoboda", legParty: legpartyHLASSD)
let mp93 = MPModel(name: "Andrea Szabóová", legParty: legpartyHLASSD)
let mp94 = MPModel(name: "Radomír Šalitroš", legParty: legpartyHLASSD)
let mp95 = MPModel(name: "Igor Šimko", legParty: legpartyHLASSD)
let mp96 = MPModel(name: "Dušan Tittel", legParty: legpartyHLASSD)
let mp97 = MPModel(name: "Erik Vlček", legParty: legpartyHLASSD)
let mp98 = MPModel(name: "Peter Žiga", legParty: legpartyHLASSD)

let mp99 = MPModel(name: "Irena Bihariová", legParty: legpartyPS)
let mp100 = MPModel(name: "Dávid Dej", legParty: legpartyPS)
let mp101 = MPModel(name: "Martin Dubéci", legParty: legpartyPS)
let mp102 = MPModel(name: "Richard Dubovický", legParty: legpartyPS)
let mp103 = MPModel(name: "Oskar Dvořák", legParty: legpartyPS)
let mp104 = MPModel(name: "Tina Gažovičová", legParty: legpartyPS)
let mp105 = MPModel(name: "Jana Hanuliaková", legParty: legpartyPS)
let mp106 = MPModel(name: "Ján Hargaš", legParty: legpartyPS)
let mp107 = MPModel(name: "Zora Jaurová", legParty: legpartyPS)
let mp108 = MPModel(name: "Beáta Jurík", legParty: legpartyPS)
let mp109 = MPModel(name: "Viera Kalmárová", legParty: legpartyPS)
let mp110 = MPModel(name: "Štefan Kišš", legParty: legpartyPS)
let mp111 = MPModel(name: "Dana Kleinert", legParty: legpartyPS)
let mp112 = MPModel(name: "Ingrid Kosová", legParty: legpartyPS)
let mp113 = MPModel(name: "Marek Lackovič", legParty: legpartyPS)
let mp114 = MPModel(name: "Darina Luščíková", legParty: legpartyPS)
let mp115 = MPModel(name: "Zuzana Mesterová", legParty: legpartyPS)
let mp116 = MPModel(name: "Natália Nash", legParty: legpartyPS)
let mp117 = MPModel(name: "Simona Petrík", legParty: legpartyPS)
let mp118 = MPModel(name: "Lucia Plaváková", legParty: legpartyPS)
let mp119 = MPModel(name: "Ondrej Prostredník", legParty: legpartyPS)
let mp120 = MPModel(name: "Michal Sabo", legParty: legpartyPS)
let mp121 = MPModel(name: "Jaroslav Spišiak", legParty: legpartyPS)
let mp122 = MPModel(name: "Tamara Stohlová", legParty: legpartyPS)
let mp123 = MPModel(name: "Michal Šimečka", legParty: legpartyPS)
let mp124 = MPModel(name: "Veronika Šrobová", legParty: legpartyPS)
let mp125 = MPModel(name: "Ivan Štefunko", legParty: legpartyPS)
let mp126 = MPModel(name: "Zuzana Števulová", legParty: legpartyPS)
let mp127 = MPModel(name: "Viliam Tankó", legParty: legpartyPS)
let mp128 = MPModel(name: "Michal Truban", legParty: legpartyPS)
let mp129 = MPModel(name: "Tomáš Valášek", legParty: legpartyPS)
let mp130 = MPModel(name: "Branislav Vančo", legParty: legpartyPS)
let mp131 = MPModel(name: "Veronika Veslárová", legParty: legpartyPS)

let mp132 = MPModel(name: "Lukáš Bužo", legParty: legpartySLOVENSKO)
let mp133 = MPModel(name: "Gábor Grendel", legParty: legpartySLOVENSKO)
let mp134 = MPModel(name: "Július Jakab", legParty: legpartySLOVENSKO)
let mp135 = MPModel(name: "Marek Krajčí", legParty: legpartySLOVENSKO)
let mp136 = MPModel(name: "Rastislav Krátky", legParty: legpartySLOVENSKO)
let mp137 = MPModel(name: "Igor Matovič", legParty: legpartySLOVENSKO)
let mp138 = MPModel(name: "Roman Mikulec", legParty: legpartySLOVENSKO)
let mp139 = MPModel(name: "Peter Pollák", legParty: legpartySLOVENSKO)
let mp140 = MPModel(name: "Jozef Pročko", legParty: legpartySLOVENSKO)
let mp141 = MPModel(name: "Veronika Remišová", legParty: legpartySLOVENSKO)
let mp142 = MPModel(name: "Michal Šipoš", legParty: legpartySLOVENSKO)
let mp143 = MPModel(name: "Anežka Škopová", legParty: legpartySLOVENSKO)
let mp144 = MPModel(name: "Richard Vašečka", legParty: legpartySLOVENSKO)
let mp145 = MPModel(name: "Anna Záborská", legParty: legpartySLOVENSKO)

let mp146 = MPModel(name: "Martina Holečková")
let mp147 = MPModel(name: "Rudolf Huliak")
let mp148 = MPModel(name: "Pavel Ľupták")
let mp149 = MPModel(name: "Ivan Ševčík")
let mp150 = MPModel(name: "Ľubomír Galko")

let currentMPs: [MPModel] = [
    mp1, mp2, mp3, mp4, mp5, mp6, mp7, mp8, mp9, mp10,
    mp11, mp12, mp13, mp14, mp15, mp16, mp17, mp18, mp19, mp20,
    mp21, mp22, mp23, mp24, mp25, mp26, mp27, mp28, mp29, mp30,
    mp31, mp32, mp33, mp34, mp35, mp36, mp37, mp38, mp39, mp40,
    mp41, mp42, mp43, mp44, mp45, mp46, mp47, mp48, mp49, mp50,
    mp51, mp52, mp53, mp54, mp55, mp56, mp57, mp58, mp59, mp60,
    mp61, mp62, mp63, mp64, mp65, mp66, mp67, mp68, mp69, mp70,
    mp71, mp72, mp73, mp74, mp75, mp76, mp77, mp78, mp79, mp80,
    mp81, mp82, mp83, mp84, mp85, mp86, mp87, mp88, mp89, mp90,
    mp91, mp92, mp93, mp94, mp95, mp96, mp97, mp98, mp99, mp100,
    mp101, mp102, mp103, mp104, mp105, mp106, mp107, mp108, mp109, mp110,
    mp111, mp112, mp113, mp114, mp115, mp116, mp117, mp118, mp119, mp120,
    mp121, mp122, mp123, mp124, mp125, mp126, mp127, mp128, mp129, mp130,
    mp131, mp132, mp133, mp134, mp135, mp136, mp137, mp138, mp139, mp140,
    mp141, mp142, mp143, mp144, mp145, mp146, mp147, mp148, mp149, mp150
]
