//
//  CurrentParl.swift
//  polCal-v2
//
//  Created by Lukas on 24/10/2024.
//

import Foundation
import SwiftData

let legpartySLOVENSKO = SVKlegPartyModel(id: 4, name: "OĽaNO")
let legpartySMERSD = SVKlegPartyModel(id: 1, name: "SMER–SD")
let legpartySNS = SVKlegPartyModel(id: 7,name: "SNS")
let legpartySAS = SVKlegPartyModel(id: 5,name: "SAS")
let legpartyKDH = SVKlegPartyModel(id: 6,name: "KDH")
let legpartyPS = SVKlegPartyModel(id: 2, name: "PS")
let legpartyHLASSD = SVKlegPartyModel(id: 3,name: "HLAS–SD")



let mp1 = SVKMPModel(name: "Vladimír Baláž", legParty: legpartySMERSD)
let mp2 = SVKMPModel(name: "Jaroslav Baška", legParty: legpartySMERSD)
let mp3 = SVKMPModel(name: "Marcela Čavojová", legParty: legpartySMERSD)
let mp4 = SVKMPModel(name: "Vladimír Faič", legParty: legpartySMERSD)
let mp5 = SVKMPModel(name: "Dušan Galis", legParty: legpartySMERSD)
let mp6 = SVKMPModel(name: "Tibor Gašpar", legParty: legpartySMERSD)
let mp7 = SVKMPModel(name: "Richard Glück", legParty: legpartySMERSD)
let mp8 = SVKMPModel(name: "Pavol Goga", legParty: legpartySMERSD)
let mp9 = SVKMPModel(name: "Jozef Habánik", legParty: legpartySMERSD)
let mp10 = SVKMPModel(name: "Augustín Hambálek", legParty: legpartySMERSD)
let mp11 = SVKMPModel(name: "Ivan Hazucha", legParty: legpartySMERSD)
let mp12 = SVKMPModel(name: "Ján Horváth", legParty: legpartySMERSD)
let mp13 = SVKMPModel(name: "Dušan Jarjabek", legParty: legpartySMERSD)
let mp14 = SVKMPModel(name: "Jozef Ježík", legParty: legpartySMERSD)
let mp15 = SVKMPModel(name: "Jozef Kačmár", legParty: legpartySMERSD)
let mp16 = SVKMPModel(name: "Michal Kapuš", legParty: legpartySMERSD)
let mp17 = SVKMPModel(name: "Daniel Karas", legParty: legpartySMERSD)
let mp18 = SVKMPModel(name: "Marián Kéry", legParty: legpartySMERSD)
let mp19 = SVKMPModel(name: "Stanislav Kubánek", legParty: legpartySMERSD)
let mp20 = SVKMPModel(name: "Ján Kvorka", legParty: legpartySMERSD)
let mp21 = SVKMPModel(name: "Boleslav Lešo", legParty: legpartySMERSD)
let mp22 = SVKMPModel(name: "Michal Lukša", legParty: legpartySMERSD)
let mp23 = SVKMPModel(name: "Zuzana Matejičková", legParty: legpartySMERSD)
let mp24 = SVKMPModel(name: "Ján Mažgút", legParty: legpartySMERSD)
let mp25 = SVKMPModel(name: "Jaroslav Mego", legParty: legpartySMERSD)
let mp26 = SVKMPModel(name: "František Petro", legParty: legpartySMERSD)
let mp27 = SVKMPModel(name: "Zuzana Plevíková", legParty: legpartySMERSD)
let mp28 = SVKMPModel(name: "Ján Podmanický", legParty: legpartySMERSD)
let mp29 = SVKMPModel(name: "Ján Richter", legParty: legpartySMERSD)
let mp30 = SVKMPModel(name: "Marián Saloň", legParty: legpartySMERSD)
let mp31 = SVKMPModel(name: "Justín Sedlák", legParty: legpartySMERSD)
let mp32 = SVKMPModel(name: "Andrej Sitkár", legParty: legpartySMERSD)
let mp33 = SVKMPModel(name: "Peter Sokol", legParty: legpartySMERSD)
let mp34 = SVKMPModel(name: "Anton Stredák", legParty: legpartySMERSD)
let mp35 = SVKMPModel(name: "Michal Stuška", legParty: legpartySMERSD)
let mp36 = SVKMPModel(name: "Peter Šuca", legParty: legpartySMERSD)
let mp37 = SVKMPModel(name: "Igor Válek", legParty: legpartySMERSD)
let mp38 = SVKMPModel(name: "Jozef Valocký", legParty: legpartySMERSD)
let mp39 = SVKMPModel(name: "Jana Vaľová", legParty: legpartySMERSD)
let mp40 = SVKMPModel(name: "Ľubomír Vážny", legParty: legpartySMERSD)
let mp41 = SVKMPModel(name: "Viliam Zahorčák", legParty: legpartySMERSD)

let mp42 = SVKMPModel(name: "Jana Bittó Cigániková", legParty: legpartySAS)
let mp43 = SVKMPModel(name: "Ondrej Dostál", legParty: legpartySAS)
let mp44 = SVKMPModel(name: "Karol Galek", legParty: legpartySAS)
let mp45 = SVKMPModel(name: "Branislav Gröhling", legParty: legpartySAS)
let mp46 = SVKMPModel(name: "Alojz Hlina", legParty: legpartySAS)
let mp47 = SVKMPModel(name: "Mária Kolíková", legParty: legpartySAS)
let mp48 = SVKMPModel(name: "Juraj Krúpa", legParty: legpartySAS)
let mp49 = SVKMPModel(name: "Vladimír Ledecký", legParty: legpartySAS)
let mp50 = SVKMPModel(name: "Vladimíra Marcinková", legParty: legpartySAS)
let mp51 = SVKMPModel(name: "Tomáš Szalay", legParty: legpartySAS)
let mp52 = SVKMPModel(name: "Marián Viskupič", legParty: legpartySAS)

let mp53 = SVKMPModel(name: "Andrej Danko", legParty: legpartySNS)
let mp54 = SVKMPModel(name: "Karol Farkašovský", legParty: legpartySNS)
let mp55 = SVKMPModel(name: "Milan Garaj", legParty: legpartySNS)
let mp56 = SVKMPModel(name: "Peter Kotlár", legParty: legpartySNS)
let mp57 = SVKMPModel(name: "Dagmar Kramplová", legParty: legpartySNS)
let mp58 = SVKMPModel(name: "Adam Lučanský", legParty: legpartySNS)
let mp59 = SVKMPModel(name: "Roman Michelko", legParty: legpartySNS)
let mp60 = SVKMPModel(name: "Dušan Muňko", legParty: legpartySNS)

let mp61 = SVKMPModel(name: "Marián Čaučík", legParty: legpartyKDH)
let mp62 = SVKMPModel(name: "Jozef Hajko", legParty: legpartyKDH)
let mp63 = SVKMPModel(name: "Ján Horecký", legParty: legpartyKDH)
let mp64 = SVKMPModel(name: "Igor Janckulík", legParty: legpartyKDH)
let mp65 = SVKMPModel(name: "František Majerský", legParty: legpartyKDH)
let mp66 = SVKMPModel(name: "Milan Majerský", legParty: legpartyKDH)
let mp67 = SVKMPModel(name: "František Mikloško", legParty: legpartyKDH)
let mp68 = SVKMPModel(name: "Peter Stachura", legParty: legpartyKDH)
let mp69 = SVKMPModel(name: "Branislav Škripek", legParty: legpartyKDH)
let mp70 = SVKMPModel(name: "Martin Šmilňák", legParty: legpartyKDH)
let mp71 = SVKMPModel(name: "Andrea Turčanová", legParty: legpartyKDH)

let mp72 = SVKMPModel(name: "Michal Bartek", legParty: legpartyHLASSD)
let mp73 = SVKMPModel(name: "Branislav Becík", legParty: legpartyHLASSD)
let mp74 = SVKMPModel(name: "Ján Blcháč", legParty: legpartyHLASSD)
let mp75 = SVKMPModel(name: "Jozef Cech", legParty: legpartyHLASSD)
let mp76 = SVKMPModel(name: "Miroslav Čellár", legParty: legpartyHLASSD)
let mp77 = SVKMPModel(name: "Dávid Demečko", legParty: legpartyHLASSD)
let mp78 = SVKMPModel(name: "Richard Eliáš", legParty: legpartyHLASSD)
let mp79 = SVKMPModel(name: "Ján Ferenčák", legParty: legpartyHLASSD)
let mp80 = SVKMPModel(name: "Štefan Gašparovič", legParty: legpartyHLASSD)
let mp81 = SVKMPModel(name: "Karol Janas", legParty: legpartyHLASSD)
let mp82 = SVKMPModel(name: "Peter Kalivoda", legParty: legpartyHLASSD)
let mp83 = SVKMPModel(name: "Ľubica Laššáková", legParty: legpartyHLASSD)
let mp84 = SVKMPModel(name: "Zdenka Mačicová", legParty: legpartyHLASSD)
let mp85 = SVKMPModel(name: "Roman Malatinec", legParty: legpartyHLASSD)
let mp86 = SVKMPModel(name: "Samuel Migaľ", legParty: legpartyHLASSD)
let mp87 = SVKMPModel(name: "Peter Náhlik", legParty: legpartyHLASSD)
let mp88 = SVKMPModel(name: "Alena Nováková", legParty: legpartyHLASSD)
let mp89 = SVKMPModel(name: "Róbert Puci", legParty: legpartyHLASSD)
let mp90 = SVKMPModel(name: "Paula Puškárová", legParty: legpartyHLASSD)
let mp91 = SVKMPModel(name: "Peter Slyško", legParty: legpartyHLASSD)
let mp92 = SVKMPModel(name: "Zdenko Svoboda", legParty: legpartyHLASSD)
let mp93 = SVKMPModel(name: "Andrea Szabóová", legParty: legpartyHLASSD)
let mp94 = SVKMPModel(name: "Radomír Šalitroš", legParty: legpartyHLASSD)
let mp95 = SVKMPModel(name: "Igor Šimko", legParty: legpartyHLASSD)
let mp96 = SVKMPModel(name: "Dušan Tittel", legParty: legpartyHLASSD)
let mp97 = SVKMPModel(name: "Erik Vlček", legParty: legpartyHLASSD)
let mp98 = SVKMPModel(name: "Peter Žiga", legParty: legpartyHLASSD)

let mp99 = SVKMPModel(name: "Irena Bihariová", legParty: legpartyPS)
let mp100 = SVKMPModel(name: "Dávid Dej", legParty: legpartyPS)
let mp101 = SVKMPModel(name: "Martin Dubéci", legParty: legpartyPS)
let mp102 = SVKMPModel(name: "Richard Dubovický", legParty: legpartyPS)
let mp103 = SVKMPModel(name: "Oskar Dvořák", legParty: legpartyPS)
let mp104 = SVKMPModel(name: "Tina Gažovičová", legParty: legpartyPS)
let mp105 = SVKMPModel(name: "Jana Hanuliaková", legParty: legpartyPS)
let mp106 = SVKMPModel(name: "Ján Hargaš", legParty: legpartyPS)
let mp107 = SVKMPModel(name: "Zora Jaurová", legParty: legpartyPS)
let mp108 = SVKMPModel(name: "Beáta Jurík", legParty: legpartyPS)
let mp109 = SVKMPModel(name: "Viera Kalmárová", legParty: legpartyPS)
let mp110 = SVKMPModel(name: "Štefan Kišš", legParty: legpartyPS)
let mp111 = SVKMPModel(name: "Dana Kleinert", legParty: legpartyPS)
let mp112 = SVKMPModel(name: "Ingrid Kosová", legParty: legpartyPS)
let mp113 = SVKMPModel(name: "Marek Lackovič", legParty: legpartyPS)
let mp114 = SVKMPModel(name: "Darina Luščíková", legParty: legpartyPS)
let mp115 = SVKMPModel(name: "Zuzana Mesterová", legParty: legpartyPS)
let mp116 = SVKMPModel(name: "Natália Nash", legParty: legpartyPS)
let mp117 = SVKMPModel(name: "Simona Petrík", legParty: legpartyPS)
let mp118 = SVKMPModel(name: "Lucia Plaváková", legParty: legpartyPS)
let mp119 = SVKMPModel(name: "Ondrej Prostredník", legParty: legpartyPS)
let mp120 = SVKMPModel(name: "Michal Sabo", legParty: legpartyPS)
let mp121 = SVKMPModel(name: "Jaroslav Spišiak", legParty: legpartyPS)
let mp122 = SVKMPModel(name: "Tamara Stohlová", legParty: legpartyPS)
let mp123 = SVKMPModel(name: "Michal Šimečka", legParty: legpartyPS)
let mp124 = SVKMPModel(name: "Veronika Šrobová", legParty: legpartyPS)
let mp125 = SVKMPModel(name: "Ivan Štefunko", legParty: legpartyPS)
let mp126 = SVKMPModel(name: "Zuzana Števulová", legParty: legpartyPS)
let mp127 = SVKMPModel(name: "Viliam Tankó", legParty: legpartyPS)
let mp128 = SVKMPModel(name: "Michal Truban", legParty: legpartyPS)
let mp129 = SVKMPModel(name: "Tomáš Valášek", legParty: legpartyPS)
let mp130 = SVKMPModel(name: "Branislav Vančo", legParty: legpartyPS)
let mp131 = SVKMPModel(name: "Veronika Veslárová", legParty: legpartyPS)

let mp132 = SVKMPModel(name: "Lukáš Bužo", legParty: legpartySLOVENSKO)
let mp133 = SVKMPModel(name: "Gábor Grendel", legParty: legpartySLOVENSKO)
let mp134 = SVKMPModel(name: "Július Jakab", legParty: legpartySLOVENSKO)
let mp135 = SVKMPModel(name: "Marek Krajčí", legParty: legpartySLOVENSKO)
let mp136 = SVKMPModel(name: "Rastislav Krátky", legParty: legpartySLOVENSKO)
let mp137 = SVKMPModel(name: "Igor Matovič", legParty: legpartySLOVENSKO)
let mp138 = SVKMPModel(name: "Roman Mikulec", legParty: legpartySLOVENSKO)
let mp139 = SVKMPModel(name: "Peter Pollák", legParty: legpartySLOVENSKO)
let mp140 = SVKMPModel(name: "Jozef Pročko", legParty: legpartySLOVENSKO)
let mp141 = SVKMPModel(name: "Veronika Remišová", legParty: legpartySLOVENSKO)
let mp142 = SVKMPModel(name: "Michal Šipoš", legParty: legpartySLOVENSKO)
let mp143 = SVKMPModel(name: "Anežka Škopová", legParty: legpartySLOVENSKO)
let mp144 = SVKMPModel(name: "Richard Vašečka", legParty: legpartySLOVENSKO)
let mp145 = SVKMPModel(name: "Anna Záborská", legParty: legpartySLOVENSKO)

let mp146 = SVKMPModel(name: "Martina Holečková")
let mp147 = SVKMPModel(name: "Rudolf Huliak")
let mp148 = SVKMPModel(name: "Pavel Ľupták")
let mp149 = SVKMPModel(name: "Ivan Ševčík")
let mp150 = SVKMPModel(name: "Ľubomír Galko")

let SVKcurrentMPs: [SVKMPModel] = [
    mp1, mp2, mp3, mp4, mp5, mp6, mp7, mp8, mp9, mp10,
    mp11, mp12, mp13, mp14, mp15, mp16, mp17, mp18, mp19, mp20,
    mp21, mp22, mp23, mp24, mp25, mp26, mp27, mp28, mp29, mp30,
    mp31, mp32, mp33, mp34, mp35, mp36, mp37, mp38, mp39, mp40,
    mp41, mp42, mp43, mp44, mp45, mp46, mp47, mp48, mp49, mp50,
    mp51, mp52, mp53, mp54, mp55, mp56, mp57, mp58, mp59, mp60,
    mp61, mp62, mp63, mp64, mp65, mp66, mp67, mp68, mp69, mp70,
    mp71, mp72, mp73, mp74, mp75, mp76, mp77, mp78, mp79, mp80,
    mp81, mp82, mp83, mp84, mp85, mp86, mp87, mp88, mp89, mp90,
    mp91, mp92, mp93, mp94, mp95, mp96, mp97, mp98, mp99, mp100,
    mp101, mp102, mp103, mp104, mp105, mp106, mp107, mp108, mp109, mp110,
    mp111, mp112, mp113, mp114, mp115, mp116, mp117, mp118, mp119, mp120,
    mp121, mp122, mp123, mp124, mp125, mp126, mp127, mp128, mp129, mp130,
    mp131, mp132, mp133, mp134, mp135, mp136, mp137, mp138, mp139, mp140,
    mp141, mp142, mp143, mp144, mp145, mp146, mp147, mp148, mp149, mp150
]
